version: '3.8'

services:
  undertaker:
    image: undertaker
    build: .
    restart: always
    ports:
      - 18018:18018
  dozzle:
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    ports:
      - 8080:8080
    environment:
      DOZZLE_NO_ANALYTICS: true